### ISSUE TITLE
Please update function to support new 9 character German perso id.

### ISSUE THREAD

**Issue by Telsidor** [derDeno/AusweisCheck#1]
This number, for example fails, cause it is < 10 characters:
5959JJNLC2
see here: https://www.onedpo.com/personal-dataset-sample-german-passport-number-download-pii-data-examples/

**Comment by torbenraab** [comment]
For the Check to work you have to use the number on the back which includes the checksum to validate the number

**Comment by derDeno** [comment]
hope it's now easier to understand with the new version.
It has also some breaking changes, please take a look
